/**
 * Shared FAQ data — used by the ConciergeSheet (full categorized list).
 * The home page has its own curated 10-question list inline in app/page.tsx.
 *
 * Cevaplar "DESTEK SORULARI 2" SSS dosyasındaki resmi SSS/web cevaplarıdır.
 * keywords: aramada bulunabilirlik için gizli eş anlamlı/SEO terimleri (PDF'teki
 * "anahtar kelimeler"). Haystack'e eklenir, UI'da gösterilmez.
 *
 * Mobile app has its own copy at /c/nikahim/mobile/app/(tabs)/support.tsx;
 * for now we sync by hand.
 */

export type FaqItem = { q: string; a: string; keywords?: string[] };
export type FaqCategory = { title: string; items: FaqItem[] };

export const fullFaqCategories: FaqCategory[] = [
  {
    title: 'Nikahım Hakkında',
    items: [
      { q: 'Nikahım nedir?', a: 'Nikahım, düğün ve nikah sürecinizi daha kolay yönetmenizi sağlayan dijital bir platformdur. Organizasyonunuzu tek bir yerden yönetebilir, etkinliğinize gelemeyen davetlilerin de uzaktan bu özel güne katılmasını sağlayabilirsiniz.',
        keywords: ['nikahım nedir', 'düğün platformu', 'nikah platformu', 'dijital düğün', 'dijital nikah', 'düğün uygulaması', 'uzaktan katılım'] },
      { q: 'Nikahım nasıl çalışır?', a: 'Nikahım, düğün veya nikahınızı tek bir yerden yönetmenizi sağlar. Etkinliğinizi oluşturduktan sonra dijital davetiyenizi hazırlayabilir, davetlilerinizin katılım durumlarını takip edebilir, masa düzeninizi planlayabilir ve ortak fotoğraf albümünüzü oluşturabilirsiniz. Gelemeyen davetlileriniz ise size özel Nikahım sayfasından canlı yayını izleyebilir, tebrik mesajı bırakabilir ve Altın Tak özelliğini kullanabilir.',
        keywords: ['nasıl çalışır', 'sistem nasıl işliyor', 'nasıl kullanılıyor', 'etkinlik yönetimi', 'canlı yayın', 'davetli takibi', 'masa planı'] },
      { q: 'Nikahım ile neler yapabilirim?', a: 'Nikahım ile düğün veya nikahınızın birçok detayını tek uygulamadan yönetebilirsiniz. Dijital davetiyenizi oluşturabilir, davetlilerinizin katılımını takip edebilir, Akıllı Masa Planlayıcısı ile oturma düzeninizi hazırlayabilir ve ortak fotoğraf albümünüzü oluşturabilirsiniz. Uzaktaki davetlileriniz ise canlı yayına katılabilir, video, sesli veya yazılı tebrik bırakabilir ve Altın Tak özelliğini kullanabilir.',
        keywords: ['özellikler', 'neler yapabilirim', 'dijital davetiye', 'fotoğraf albümü', 'canlı yayın', 'tebrik mesajı', 'altın tak', 'masa planı'] },
      { q: 'Nikahım sadece düğünler için mi?', a: 'Hayır. Nikahım’ı hem düğününüz hem de nikah töreniniz için kullanabilirsiniz. Farklı şehirlerde birden fazla düğün yapıyorsanız her biri için ayrı etkinlik de oluşturabilirsiniz. Şu an için nişan, kına gibi diğer etkinlik türleri desteklenmemektedir.',
        keywords: ['sadece düğün mü', 'nikah töreni', 'nişan', 'kına', 'iki düğün', 'farklı şehir', 'etkinlik türü'] },
      { q: 'Nikahım’ı bilgisayardan kullanabilir miyim?', a: 'Nikahım’ın tüm özelliklerini uygulamadan kullanabilirsiniz. Daha geniş bir ekranda çalışmayı tercih ederseniz Akıllı Masa Planlayıcısı ve Fotoğraf Albümü bölümlerine bilgisayarınızdan da erişebilirsiniz. Masa düzeninizi yönetebilir, albümünüzü düzenleyebilir ve fotoğraflarınızı bilgisayarınıza indirebilirsiniz.',
        keywords: ['bilgisayar', 'masaüstü', 'web', 'laptop', 'pc', 'masa planlayıcısı', 'fotoğraf albümü', 'fotoğraf indirme'] },
      { q: 'Nikahım hem Android hem iPhone’da çalışıyor mu?', a: 'Evet. Nikahım hem Android hem de iPhone cihazlarda kullanılabilir. Uygulamayı destekleyen bir tablette de kullanabilirsiniz.',
        keywords: ['android', 'iphone', 'ios', 'tablet', 'ipad', 'uyumluluk', 'cihaz', 'samsung'] },
      { q: 'Nikahım güvenilir mi?', a: 'Nikahım’da etkinliğinize ait bilgiler kalıcı olarak tutulmaz. Düğün veya nikah tarihinizden 60 gün sonra etkinliğe ait bilgiler ve kayıtlar sistemden otomatik olarak silinir. Kişisel bilgileriniz izniniz olmadan reklam amacıyla kullanılmaz veya üçüncü kişilerle paylaşılmaz.',
        keywords: ['güvenilir mi', 'güvenli mi', 'veri güvenliği', 'gizlilik', '60 gün', 'veri silme', 'kişisel bilgi'] },
      { q: 'Nikahım ücretsiz olarak denenebilir mi?', a: 'Evet. Nikahım uygulamasını ücretsiz olarak indirebilir ve sunulan özellikleri uygulama içerisinden inceleyebilirsiniz. Etkinliğinizde özellikleri kullanmaya başlamak için ise size uygun bir paket satın almanız gerekir. Hesap oluşturmak tamamen ücretsizdir.',
        keywords: ['ücretsiz', 'deneme', 'ücretsiz deneme', 'uygulama indirme', 'hesap ücretsiz', 'paket almadan', 'inceleme'] },
    ],
  },
  {
    title: 'Hesap ve Etkinlik',
    items: [
      { q: 'Davetlilerimin uygulama indirmesi gerekiyor mu?', a: 'Hayır. Davetlilerinizin uygulama indirmesine gerek yoktur. Gönderdiğiniz Nikahım bağlantısını telefon, tablet veya bilgisayarlarından açarak canlı yayına katılabilir, fotoğraf yükleyebilir, tebrik mesajı bırakabilir ve davetlilere açık diğer özellikleri kullanabilirler.',
        keywords: ['davetli uygulama', 'uygulama indirme', 'misafir', 'link', 'tarayıcı', 'app gerekli mi', 'annem uygulama'] },
      { q: 'Davetlilerin üye olması gerekiyor mu?', a: 'Hayır. Davetlilerinizin hesap oluşturmasına gerek yoktur. Paylaştığınız bağlantıyı açıp yalnızca ad ve soyad bilgilerini girerek etkinlik sayfanıza ulaşabilirler.',
        keywords: ['üyelik', 'hesap', 'davetli üye', 'ad soyad', 'kayıt', 'misafir girişi', 'üye olmadan'] },
      { q: 'Düğün tarihimi/saatimi/mekânımı sonradan değiştirebilir miyim?', a: 'Evet. Etkinliğinizin tarihini, saatini ve mekân bilgilerini uygulama üzerinden istediğiniz zaman güncelleyebilirsiniz. Paket satın aldıktan sonra da bu bilgileri değiştirebilirsiniz.',
        keywords: ['tarih değiştirme', 'saat değiştirme', 'mekan değiştirme', 'düğün ertelendi', 'etkinlik güncelleme', 'yanlış tarih'] },
      { q: 'Gelin ve damat isimlerini değiştirebilir miyim?', a: 'Evet. Etkinliğinizde görünen gelin ve damat isimlerini uygulama üzerinden istediğiniz zaman güncelleyebilirsiniz.',
        keywords: ['gelin', 'damat', 'isim değiştirme', 'çift bilgileri', 'isim yanlış', 'isim güncelleme'] },
      { q: 'Aynı hesapta birden fazla etkinlik oluşturabilir miyim?', a: 'Evet. Aynı hesabınız üzerinden en fazla iki ayrı düğün veya nikah etkinliği oluşturabilirsiniz. Örneğin Nikah + Düğün ya da iki farklı şehirdeki düğününüzü ayrı ayrı ekleyebilirsiniz.',
        keywords: ['iki etkinlik', 'birden fazla etkinlik', 'ikinci düğün', 'ikinci nikah', 'aynı hesap', 'etkinlik limiti'] },
      { q: 'Eşim de aynı etkinliği yönetebilir mi?', a: 'Evet. Eşiniz Nikahım uygulamasını kendi telefonuna indirip aynı hesap bilgileriyle giriş yaparak etkinliğinizi sizinle birlikte yönetebilir. Güvenlik için hesap bilgilerinizi eşiniz dışında üçüncü kişilerle paylaşmamanızı öneririz.',
        keywords: ['eş', 'ortak yönetim', 'aynı hesap', 'ikinci telefon', 'hesap paylaşımı', 'birlikte yönetme'] },
      { q: 'Etkinliği yanlışlıkla silersem geri getirebilir miyim?', a: 'Etkinliğinizi yanlışlıkla sildiyseniz Nikahım Destek ile iletişime geçin. Ekibimiz durumunuzu kontrol ederek size yardımcı olacaktır.',
        keywords: ['etkinlik silme', 'yanlışlıkla sildim', 'silinen etkinlik', 'geri getirme', 'kurtarma', 'destek'] },
      { q: 'Davetli bağlantım ne zaman oluşur ve ne zaman aktif olur?', a: 'Etkinliğinizi oluşturup paket seçiminizi tamamladıktan sonra size özel davetli bağlantınız birkaç saniye içinde hazırlanır. Bu bağlantı düğüne 3 gün kalana kadar davetlilerinizin katılım bilgilerini toplar; 3 gün kala ise aynı sayfa canlı yayın, Altın Tak, tebrik mesajları, albüm ve fotoğraf yükleme özelliklerinin bulunduğu etkinlik sayfanıza dönüşür. Tek bağlantı, tüm süreç.',
        keywords: ['davetli linki', 'etkinlik linki', 'bağlantı ne zaman', '3 gün', 'rsvp', 'aktif', 'tek link', 'yeni link'] },
      { q: 'Etkinlik sayfamı düğünden önce önizleyebilir miyim?', a: 'Evet. Nikahım ana sayfasındaki örnek düğün sayfasını inceleyebilir veya kendi etkinliğinizi oluşturduktan sonra uygulamadaki Düğünüm/Nikahım bölümünden davetlilerinizin göreceği sayfayı önizleyebilirsiniz.',
        keywords: ['önizleme', 'preview', 'test', 'davetli sayfası', 'örnek düğün', 'düğünüm', 'nikahım'] },
    ],
  },
  {
    title: 'Dijital Davetiye ve Davetli Takibi',
    items: [
      { q: 'Dijital davetiye nasıl oluşturulur?', a: 'Etkinliğinizi oluştururken Nikahım’daki onlarca hazır dijital davetiye tasarımından size uygun olanı seçebilirsiniz. Gelin-damat, tarih, saat ve mekân gibi etkinlik bilgileriniz seçtiğiniz tasarıma otomatik olarak eklenir ve davetiyeniz hazır hale gelir.',
        keywords: ['dijital davetiye', 'davetiye oluşturma', 'davetiye tasarımı', 'şablon', 'hazır davetiye', 'online davetiye'] },
      { q: 'Davetiyeyi kendim tasarlayabilir miyim / şablonu değiştirebilir miyim?', a: 'Hazır Nikahım şablonlarının tasarımını doğrudan değiştiremezsiniz; ancak onlarca farklı seçenek arasından size en uygun olanı seçebilirsiniz. Etkinliğinizi oluşturduktan sonra seçtiğiniz davetiye tasarımını en fazla 3 kez değiştirebilirsiniz. Kendi hazırladığınız bir davetiyeniz varsa onu da sisteme yükleyerek kullanabilirsiniz.',
        keywords: ['davetiye tasarımı', 'özel davetiye', 'kendi davetiyem', 'şablon değiştirme', '3 kez', 'davetiye yükleme'] },
      { q: 'Davetiyeyi WhatsApp / Instagram’dan gönderebilir miyim?', a: 'Evet. Davetiyenizi ve size özel davetli bağlantınızı WhatsApp veya Instagram üzerinden kolayca paylaşabilirsiniz. Paylaşım sırasında göndereceğiniz mesajı da kendiniz düzenleyebilirsiniz. Şu an için doğrudan SMS gönderimi desteklenmemektedir.',
        keywords: ['whatsapp', 'instagram', 'davetiye gönderme', 'davetiye paylaşma', 'sms', 'davetli linki', 'paylaş'] },
      { q: 'Düğün konumu / Google Maps ekleyebilir miyim?', a: 'Evet. Etkinliğinizi oluştururken düğün veya nikah mekânınızın konumunu Google Maps üzerinden ekleyebilirsiniz. Davetlileriniz, etkinlik sayfanızdaki Yol Tarifi seçeneğine dokunarak mekân konumuna kolayca ulaşabilir.',
        keywords: ['konum', 'düğün konumu', 'google maps', 'yol tarifi', 'adres', 'harita', 'mekan'] },
      { q: 'Davetli Takibi nedir?', a: 'Davetli Takibi ile davet listenizi ve katılım durumlarını tek bir yerden takip edebilirsiniz. Kimlerin davet edildiğini, kimlerin katılacağını, kimlerin gelemeyeceğini ve henüz yanıt vermeyen davetlilerinizi uygulama üzerinden kolayca görebilirsiniz.',
        keywords: ['davetli takibi', 'rsvp', 'katılım', 'gelecek', 'gelmeyecek', 'davetli listesi', 'katılım durumu'] },
      { q: 'Davetliler geleceklerini nasıl bildirir?', a: 'Davetlileriniz, kendileriyle paylaştığınız Nikahım bağlantısını açarak katılıp katılamayacaklarını doğrudan bildirebilir. Verdikleri cevap otomatik olarak Davetli Takibi bölümüne yansır; katılırken kaç kişiyle geleceklerini de belirtebilirler.',
        keywords: ['katılıyorum', 'katılamıyorum', 'rsvp', 'cevap', 'kaç kişi', 'yanında gelecek', 'katılım bildirme'] },
      { q: 'Davetli listemi Excel’den aktarabilir miyim?', a: 'Evet. Hazır bir davetli listeniz varsa Excel dosyanızı Akıllı Masa Planlayıcısı üzerinden içe aktarabilirsiniz. Davetlilerinizi ayrıca telefon rehberinizden seçebilir veya tek tek manuel olarak da ekleyebilirsiniz.',
        keywords: ['excel', 'davetli listesi', 'liste yükleme', 'içe aktarma', 'toplu ekleme', 'rehber', 'manuel ekleme'] },
      { q: 'Cevap vermeyen davetlilere hatırlatma gönderebilir miyim?', a: 'Hatırlatma mesajlarını şu an için sizin göndermeniz gerekir. Henüz cevap vermeyen davetlilerinize uygun gördüğünüz zaman yeniden ulaşarak katılım durumlarını bildirmelerini hatırlatabilirsiniz. Henüz yanıt vermeyenler uygulamada “Henüz Bildirmedi” olarak görünür.',
        keywords: ['hatırlatma', 'cevap vermeyen', 'henüz bildirmedi', 'rsvp hatırlatma', 'otomatik mesaj', 'davetli hatırlatma'] },
    ],
  },
  {
    title: 'Canlı Yayın',
    items: [
      { q: 'Canlı yayın için profesyonel ekipmana ihtiyacım var mı?', a: 'Hayır. Profesyonel kameraya ihtiyacınız yok. Nikahım uygulamasının yüklü olduğu uygun bir telefonla canlı yayınınızı başlatabilirsiniz; temel yayın ayarlarını Nikahım sizin için otomatik olarak yönetir. İyi bir yayın için stabil internet ve yeterli şarj önerilir; daha sabit görüntü için tripod da kullanabilirsiniz.',
        keywords: ['profesyonel kamera', 'kamera', 'ekipman', 'telefon yeterli', 'tripod', 'kameraman', 'yayın ekipmanı'] },
      { q: 'Düğünümü nasıl canlı yayınlarım?', a: 'Etkinliğinizi oluşturduktan sonra uygulamadaki Canlı Yayın bölümüne girmeniz yeterli. Nikahım kamera, mikrofon ve bağlantı kalitesi gibi gerekli kontrolleri sizin için otomatik olarak yapar. Her şey hazır olduğunda tek dokunuşla canlı yayına geçebilirsiniz.',
        keywords: ['canlı yayın', 'yayın başlatma', 'nasıl yayın yapılır', 'kamera', 'mikrofon', 'yayına başla', 'yayına geç'] },
      { q: 'Test yayını yapabilir miyim, süremden düşer mi?', a: 'Evet. Canlı Yayın bölümünden 1 dakikalık test yayını yapabilirsiniz. Böylece etkinlik mekânındaki bağlantınızı kontrol edebilir ve önerilen yayın kalitesini görebilirsiniz. Test yayını sayısında sınır yoktur ve paketinizdeki canlı yayın süresini kullanmaz.',
        keywords: ['test yayını', 'deneme yayını', '1 dakika', 'test süreden düşer mi', 'sınırsız test', 'ücretsiz test'] },
      { q: 'Canlı yayın kayıt altına alınıyor mu?', a: 'Evet. Canlı yayınınız otomatik olarak kayıt altına alınır. Yayın sırasında ara verir veya bağlantı kesintisi yaşarsanız kayıt birden fazla video parçası halinde oluşabilir. Kayıtlarınızı 60 gün boyunca izleyebilir veya indirebilirsiniz.',
        keywords: ['yayın kaydı', 'kayıt', 'video', '60 gün', 'düğün videosu', 'tekrar izle', 'indirme'] },
      { q: 'İnternet kesilirse / bağlantı koparsa ne olur?', a: 'Bağlantınız kesilirse o ana kadarki yayın kaybolmaz; kayıt altına alınır. Nikahım yeniden bağlanmayı otomatik olarak dener ve internet geri geldiğinde yayın kaldığınız yerden devam eder. Kısa süreli kesintilerde sizin bir şey yapmanıza gerek kalmaz.',
        keywords: ['internet kesildi', 'bağlantı koptu', 'yeniden bağlanma', 'kesilirse', 'koparsa', 'otomatik bağlantı', 'yayın devamı'] },
      { q: 'Yayın sırasında arama gelirse veya telefon kilitlenirse ne olur?', a: 'Canlı yayın sırasında Nikahım, telefonunuzun otomatik olarak ekran kilidine geçmesini engeller; siz ekranı elle kilitlemediğiniz sürece yayın kesilmez. Gelen aramaların yayını etkilememesi için yayına başlamadan önce telefonunuzu Rahatsız Etme moduna almanızı öneriyoruz.',
        keywords: ['arama gelirse', 'telefon kilitlenirse', 'ekran kilidi', 'rahatsız etme', 'dnd', 'yayın kesilir mi', 'ekran kapanması'] },
      { q: 'Telefonun şarjı biterse / başka telefona geçebilir miyim?', a: 'Telefonunuz kapanırsa canlı yayın durur; ancak o ana kadarki yayın kaybolmaz ve kayıt altına alınır. Telefonunuzu yeniden açtıktan veya Nikahım uygulamasının yüklü olduğu başka bir cihaza aynı hesapla giriş yaptıktan sonra yayına devam edebilirsiniz.',
        keywords: ['şarj', 'pil', 'telefon kapandı', 'başka telefon', 'cihaz değiştirme', 'powerbank', 'yayına devam'] },
      { q: 'Canlı yayın kalitesi nedir? Her zaman 1080p olur mu?', a: 'Nikahım, bağlantı kalitenizi test ederek sizin için uygun yayın çözünürlüğünü otomatik olarak önerir; dilerseniz çözünürlüğü kendiniz de değiştirebilirsiniz. En yüksek yayın kalitesi 1080p Full HD’dir. İnternet bağlantınız yetersizse daha yüksek çözünürlük donmaya neden olabilir; bu yüzden sistemin önerdiği çözünürlüğü kullanmanız daha akıcı bir yayın sağlar.',
        keywords: ['yayın kalitesi', '1080p', 'full hd', 'çözünürlük', 'görüntü kalitesi', 'bağlantı testi', 'donma'] },
      { q: 'Yayına ara verebilir miyim, kalan sürem ne olur?', a: 'Evet. Dilediğiniz zaman yayına ara verebilir ve kalan yayın sürenizi daha sonra kullanabilirsiniz. Ara verdiğiniz ana kadar olan yayın ayrıca kayıt altına alınır. Bağlantı kopmalarında da süre hakkınızdan kayıp olmaz.',
        keywords: ['yayına ara', 'duraklatma', 'yayın süresi', 'kalan süre', 'devam et', 'süre yanar mı'] },
      { q: 'İzleyici limiti aşılırsa ne olur, ek izleyici/süre alabilir miyim?', a: 'İzleyici limitinize ulaşıldığında Nikahım sizi yayın sırasında bilgilendirir. Ek izleyicileri kabul ederseniz yayını kesmeden devam edebilirsiniz; limit üzerindeki kullanım yayın sonrasında ek izleyici paketi üzerinden tamamlanır. Aynı şekilde ek yayın süresi de satın alabilirsiniz.',
        keywords: ['izleyici limiti', 'limit doldu', 'ek izleyici', 'ek süre', 'kapasite', 'yayın kesilmesi'] },
      { q: 'Canlı yayın mobil veriyle ne kadar internet harcar?', a: '1080p canlı yayın yaklaşık 30 MB/dakika veri kullanabilir. Yaklaşık olarak 30 dakika ~1 GB, 90 dakika ~2,7 GB, 180 dakika ~5,4 GB. Daha düşük çözünürlükte tüketim azalır; mümkün olduğunda güçlü ve stabil bir Wi-Fi bağlantısı kullanmanızı öneriyoruz.',
        keywords: ['mobil veri', 'internet kullanımı', '30mb', 'gb', 'kaç gb', 'wifi', '4g', '5g', 'veri tüketimi'] },
      { q: 'Canlı yayın herkese açık mı, YouTube’da görünür mü?', a: 'Bu tercihi siz belirlersiniz; etkinliğinizi oluştururken sayfanızın herkese açık olup olmayacağını seçebilirsiniz. Canlı yayınınız YouTube veya başka bir açık video platformunda yayınlanmaz; yalnızca Nikahım’da etkinliğiniz için oluşturulan özel sayfa üzerinden izlenir.',
        keywords: ['herkese açık', 'gizlilik', 'youtube', 'google', 'public', 'yayın görünürlüğü', 'özel sayfa'] },
    ],
  },
  {
    title: 'Akıllı Masa Planlayıcısı',
    items: [
      { q: 'Akıllı Masa Planlayıcısı nedir ve nasıl çalışır?', a: 'Akıllı Masa Planlayıcısı, davetlilerinizi gruplarınıza ve belirlediğiniz özel kurallara göre masalara otomatik olarak yerleştirir. Önce salonunuzdaki masaları ve kapasitelerini oluşturursunuz; sistem sonra davetli listenizi, gruplarınızı ve kurallarınızı dikkate alarak en uygun oturma planını hazırlar. Aileleri veya arkadaş gruplarını birlikte tutabilir, yan yana oturmasını istemediğiniz kişileri ayırabilirsiniz.',
        keywords: ['masa planlayıcısı', 'masa planı', 'oturma düzeni', 'otomatik yerleştirme', 'grup', 'kısıt', 'akıllı masa'] },
      { q: 'Belirli kişileri aynı masaya koyabilir / ayrı tutabilir miyim?', a: 'Evet. Mutlaka birlikte oturmasını istediğiniz kişileri veya birlikte oturmasını istemediğiniz kişileri belirleyebilirsiniz. Akıllı Masa Planlayıcısı bu kuralları dikkate alarak kişileri aynı masaya ya da farklı masalara yerleştirir. Örneğin “Ayşe ve Fatma aynı masada olsun” veya “Ahmet ve Mehmet aynı masada olmasın” diyebilirsiniz.',
        keywords: ['aynı masa', 'ayrı masa', 'birlikte oturma', 'yan yana', 'kısıt', 'kural', 'aile birlikte', 'arkadaş grubu'] },
      { q: 'Masa sayısını, kapasitesini ve şeklini belirleyebilir miyim?', a: 'Evet. İhtiyacınız kadar masa oluşturabilirsiniz; masa sayısında bir limit yoktur. Her masanın kişi kapasitesini ve şeklini (yuvarlak, kare veya dikdörtgen) ayrı ayrı belirleyebilir, sahnenin yerini de sürükle-bırak yöntemiyle konumlandırabilirsiniz.',
        keywords: ['masa sayısı', 'masa kapasitesi', 'sandalye', 'yuvarlak masa', 'dikdörtgen masa', 'sahne', 'salon planı'] },
      { q: 'Otomatik yerleşimden sonra düzenleme yapabilir, planı yazdırabilir miyim?', a: 'Evet. Akıllı Masa Planlayıcısı planınızı oluşturduktan sonra son karar sizindir; davetlileri sürükle-bırak yöntemiyle başka masalara taşıyabilirsiniz. Hazırladığınız masa planını PDF olarak indirip yazdırabilir veya düğün salonunuzla paylaşabilirsiniz.',
        keywords: ['manuel düzenleme', 'sürükle bırak', 'davetli taşıma', 'pdf', 'yazdırma', 'salonla paylaşma', 'çıktı'] },
      { q: 'Davetli katılım (RSVP) bilgileri masa planına otomatik yansır mı?', a: 'Evet. Davetlileriniz katılım durumlarını bildirdikçe bu bilgiler Masa Planlayıcısı’na otomatik olarak yansır. Son dakika değişikliklerinde de masa planınızı istediğiniz zaman güncelleyebilirsiniz.',
        keywords: ['rsvp', 'katılım', 'otomatik yansıma', 'son dakika', 'güncelleme', 'senkronizasyon'] },
    ],
  },
  {
    title: 'Tebrik Mesajları',
    items: [
      { q: 'Tebrik mesajı nedir ve davetliler nasıl gönderir?', a: 'Tebrik Mesajları, davetlilerinizin size video, sesli veya yazılı olarak güzel dileklerini iletebildiği dijital bir anı alanıdır. Davetlileriniz etkinlik sayfanızdaki Tebrik Et bölümüne girerek video, sesli veya yazılı mesaj seçeneklerinden birini seçebilir ve tebriklerini doğrudan size gönderebilir. Uygulama veya üyelik gerekmez.',
        keywords: ['tebrik mesajı', 'tebrik et', 'video mesaj', 'sesli mesaj', 'yazılı mesaj', 'tebrik gönderme'] },
      { q: 'Video ve sesli tebriklerin süresi ne kadar?', a: 'Video tebrik mesajları en fazla 30 saniye, sesli tebrik mesajları ise en fazla 60 saniye olabilir. Bir davetli birden fazla tebrik mesajı gönderebilir.',
        keywords: ['video süresi', '30 saniye', 'sesli süre', '60 saniye', 'birden fazla mesaj', 'mesaj limiti'] },
      { q: 'Gelen tebrikleri kimler görebilir?', a: 'Tebrik mesajlarınız yalnızca sizin tarafınızdan Nikahım uygulaması üzerinden görüntülenebilir. Diğer davetliler size gönderilen mesajları göremez. Tebrik mesajları anonim gönderilemez; gönderen davetlinin adı ve soyadı görünür.',
        keywords: ['tebrik gizliliği', 'kim görebilir', 'özel mesaj', 'anonim', 'gönderen', 'sadece çift'] },
      { q: 'Tebrik mesajlarını indirebilir miyim, ne kadar saklanır?', a: 'Evet. Tüm video, sesli ve yazılı tebriklerinizi tek seferde ZIP dosyası olarak indirebilirsiniz. Tebrik mesajlarınız düğün veya nikah tarihinizden sonra 60 gün boyunca Nikahım’da saklanır; kalıcı tutmak istediklerinizi bu süre içinde indirmenizi öneririz.',
        keywords: ['tebrik indirme', 'zip', 'toplu indirme', '60 gün', 'saklama süresi', 'video indirme'] },
      { q: 'Uygunsuz bir tebrik mesajını silebilir miyim?', a: 'Evet. Görmek veya saklamak istemediğiniz tebrik mesajlarını uygulama üzerinden silebilirsiniz. Davetliler gönderdikleri mesajları kendileri silemez; silme yetkisi yalnızca çifte aittir.',
        keywords: ['uygunsuz mesaj', 'mesaj silme', 'tebrik silme', 'istenmeyen mesaj', 'moderasyon'] },
    ],
  },
  {
    title: 'Altın Takma',
    items: [
      { q: 'Altın Tak özelliği nedir?', a: 'Altın Tak, düğün veya nikahınıza gelemeyen davetlilerinizin size uzaktan altın takabilmesini sağlar. Davetliniz takmak istediği altını seçer ve güncel TL karşılığını doğrudan sizin banka hesabınıza gönderir.',
        keywords: ['altın tak', 'dijital altın', 'online altın', 'uzaktan altın', 'düğün altını', 'para transferi'] },
      { q: 'Online altın takma nasıl çalışır?', a: 'Davetliniz etkinlik sayfanızdaki Altın Tak bölümünden takmak istediği altını seçer; Nikahım seçilen altının güncel TL karşılığını gösterir. Davetli daha sonra kendi bankacılık uygulaması üzerinden bu tutarı doğrudan sizin hesabınıza havale/EFT ile gönderir ve “Para Gönderimini Tamamladım” seçeneğiyle işaretler.',
        keywords: ['online altın', 'nasıl çalışır', 'iban', 'havale', 'eft', 'banka transferi', 'altın fiyatı'] },
      { q: 'Davetli hangi altın türlerini seçebilir, kendi tutarını belirleyebilir mi?', a: 'Davetlileriniz Gram, Çeyrek, Yarım veya Tam Altın seçeneklerinden birini tercih edebilir; ayrıca kendi nakit tutarlarını da belirleyebilirler. Altın fiyatları güvenilir kaynaklardan alınır ve saatlik olarak güncellenir.',
        keywords: ['altın türleri', 'gram altın', 'çeyrek altın', 'yarım altın', 'tam altın', 'özel miktar', 'nakit tutar'] },
      { q: 'Para doğrudan bana mı geliyor, Nikahım komisyon alıyor mu?', a: 'Evet, para doğrudan çiftin banka hesabına gönderilir; Nikahım para transferine hiçbir aşamada aracılık etmez ve komisyon almaz. Transfer, davetlinin kendi bankacılık uygulamasından doğrudan sizin banka hesabınıza yapılır.',
        keywords: ['para bana mı', 'doğrudan hesap', 'komisyon', 'aracılık', 'kesinti', 'iban ödeme'] },
      { q: 'Paranın hesabıma ulaştığını nasıl anlarım?', a: 'Davetliniz “Para Gönderimini Tamamladım” seçeneğine bastığında işlem Nikahım’da tamamlandı olarak görünür. Ancak Nikahım banka transferlerini göremediği için bu bildirim davetlinin beyanına dayanır; paranın hesabınıza gerçekten ulaştığını kendi banka hesabınızdan kontrol etmeniz gerekir.',
        keywords: ['para geldi mi', 'transfer tamamlandı', 'gönderimi tamamladım', 'banka kontrolü', 'takip'] },
      { q: 'Banka hesabı gelinin mi damadın mı olabilir?', a: 'Banka hesabı gelin veya damat adına olabilir; üçüncü bir kişiye ait banka hesabı Altın Tak için kullanılamaz. IBAN bilginizi ve hesap sahibini (Gelin/Damat) Düğünüm/Nikahım bölümünden istediğiniz zaman güncelleyebilirsiniz.',
        keywords: ['gelin iban', 'damat iban', 'banka hesabı', 'iban değiştirme', 'üçüncü kişi', 'hesap sahibi'] },
      { q: 'Altın takmak güvenli mi, kartla ödeme yapılabilir mi?', a: 'Altın Tak sırasında para Nikahım’a gönderilmez; davetli transferi kendi bankacılık uygulamasından doğrudan çiftin banka hesabına gerçekleştirir. Kartla ödeme kullanılmaz; işlem havale/EFT/FAST ile TL üzerinden yapılır. Nikahım banka bilgilerinize erişmez ve parayı tutmaz.',
        keywords: ['güvenli mi', 'kart', 'kredi kartı', 'havale', 'eft', 'fast', 'para güvenliği', 'döviz'] },
    ],
  },
  {
    title: 'Fotoğraf Albümü',
    items: [
      { q: 'Ortak düğün albümü nedir, kimler yükleyebilir?', a: 'Ortak Düğün Albümü, sizin ve davetlilerinizin gün boyunca çektiği fotoğrafları tek bir dijital albümde bir araya getirir. Hem siz hem de davetlileriniz albüme fotoğraf yükleyebilir; davetliler için uygulama indirmek gerekmez, QR kod veya paylaştığınız bağlantı yeterlidir.',
        keywords: ['ortak albüm', 'düğün albümü', 'fotoğraf albümü', 'kim yükleyebilir', 'qr kod', 'davetli fotoğrafı'] },
      { q: 'Davetli kaç fotoğraf yükleyebilir, toplam kapasite nedir?', a: 'Bir davetli tek seferde en fazla 25, toplamda ise 100 fotoğraf yükleyebilir. Tüm Nikahım paketlerinde Ortak Düğün Albümü 1000 fotoğrafa kadar kapasite sunar; daha fazlası için ek fotoğraf paketi satın alarak kapasitenizi artırabilirsiniz.',
        keywords: ['fotoğraf limiti', '25 fotoğraf', '100 fotoğraf', '1000 fotoğraf', 'albüm kapasitesi', 'ek fotoğraf'] },
      { q: 'HEIC fotoğraflar destekleniyor mu, kalite düşürülüyor mu?', a: 'Evet, HEIC fotoğraf formatı desteklenmektedir. Nikahım yüklediğiniz fotoğrafların kalite veya çözünürlüğünü düşürmez; fotoğraflarınız orijinal çözünürlüğünde saklanır. Şu an için albüme video yüklenemez, yalnızca fotoğraf desteklenir.',
        keywords: ['heic', 'iphone fotoğraf', 'fotoğraf kalitesi', 'çözünürlük', 'orijinal', 'video yükleme', 'sıkıştırma'] },
      { q: 'Davetlinin yüklediği fotoğraf hemen görünür mü / onay nasıl çalışır?', a: 'Hayır. Davetlilerin yüklediği fotoğraflar doğrudan yayınlanmaz; önce sizin onayınıza gelir. Yalnızca onayladığınız kareler etkinlik sayfanızdaki albümde diğer davetlilerle paylaşılır. İstemediğiniz bir fotoğrafı Gizle olarak işaretleyebilir veya silebilirsiniz.',
        keywords: ['fotoğraf onayı', 'hemen yayınlanır mı', 'moderasyon', 'gizle', 'gizli fotoğraf', 'onay'] },
      { q: 'Fotoğrafları tek seferde indirebilir, ne kadar saklanır?', a: 'Evet. Albümünüzdeki tüm fotoğrafları tek seferde ZIP dosyası olarak, uygulamadan veya bilgisayarınızdan indirebilirsiniz. Fotoğraflarınız etkinlik tarihinden itibaren 60 gün boyunca saklanır; saklamak istediklerinizi bu süre dolmadan indirmenizi öneririz.',
        keywords: ['fotoğraf indirme', 'toplu indirme', 'zip', '60 gün', 'albüm saklama', 'bilgisayar'] },
      { q: 'Albümde kapak fotoğrafı seçebilir miyim?', a: 'Evet. Albümde ilk gösterilecek kapak fotoğrafını siz seçebilirsiniz. Beğendiğiniz fotoğrafları favori olarak da işaretleyip daha sonra yalnızca favorilerinizi görüntüleyebilir veya indirebilirsiniz.',
        keywords: ['kapak fotoğrafı', 'başlangıç fotoğrafı', 'favori', 'ilk fotoğraf', 'sıralama'] },
    ],
  },
  {
    title: 'Fotoğraf Baskısı',
    items: [
      { q: 'Albümdeki fotoğrafların baskısını alabilir miyim?', a: 'Evet. Fotoğrafçınız Nikahım Fotoğrafçı Paneli’ni kullanıyorsa, albümünüzdeki fotoğrafları doğrudan baskıya gönderebilirsiniz. Baskı talepleri fotoğrafçınızın paneline iletilir ve fotoğrafçınız talepleri buradan takip edebilir. Nikahım fotoğrafçınızdan bu işlem için komisyon almaz.',
        keywords: ['fotoğraf baskısı', 'baskı', 'fotoğrafçı', 'fotoğrafçı paneli', 'çıktı', 'albümden baskı'] },
      { q: 'Baskı fiyatlarını ve boyutlarını kim belirliyor?', a: 'Baskı boyutlarını ve fiyatlarını fotoğrafçınız belirler ve Fotoğrafçı Paneli’ne ekler; siz veya davetlileriniz baskı talebi oluştururken mevcut seçenekleri ve güncel fiyatları görerek seçim yaparsınız. Baskı ücreti Nikahım paketlerine dahil değildir ve doğrudan fotoğrafçıya ödenir.',
        keywords: ['baskı fiyatı', 'baskı boyutu', 'fotoğrafçı fiyatı', 'pakete dahil', 'ödeme', 'ebat'] },
      { q: 'Kendi fotoğrafçımla çalışabilir miyim, davetliler baskı isteyebilir mi?', a: 'Evet. Fotoğrafçınızı siz seçersiniz; Nikahım belirli bir fotoğrafçı atamaz. Fotoğrafçınız Nikahım Fotoğrafçı Paneli’ni kullandığında baskı talepleriniz doğrudan kendisine ulaşır. Davetlileriniz de kendi yükledikleri fotoğraflar için baskı talebi oluşturabilir.',
        keywords: ['kendi fotoğrafçım', 'fotoğrafçı seçimi', 'davetli baskısı', 'baskı talebi', 'fotoğrafçı paneli'] },
    ],
  },
  {
    title: 'Paketler ve Ödeme',
    items: [
      { q: 'Paketler arasındaki fark nedir?', a: 'Nikahım’da ihtiyaçlarınıza göre üç paket bulunur: Nikah (30 dakika yayın, 100 izleyici), Düğün (90 dakika yayın, 200 izleyici) ve Şölen (180 dakika yayın, 300 izleyici). Canlı Yayın, Fotoğraf Albümü, Tebrik Mesajları ve Altın Tak tüm paketlerde bulunur. Akıllı Masa Planlayıcısı ve Fotoğrafçı Paneli ise Düğün ve Şölen paketlerine dahildir.',
        keywords: ['paketler', 'nikah paketi', 'düğün paketi', 'şölen paketi', 'paket farkı', 'yayın süresi', 'izleyici limiti', 'masa planlayıcısı', 'fotoğrafçı paneli'] },
      { q: 'Hangi paket bana uygun?', a: 'Etkinliğinizin büyüklüğüne ve yayın ihtiyacınıza göre seçim yapabilirsiniz. Kısa ve sade bir nikah için Nikah, standart bir düğün için Düğün, daha kalabalık ve uzun süreli organizasyonlar için ise Şölen Paketi daha uygun olabilir.',
        keywords: ['hangi paket', 'paket seçimi', 'paket önerisi', 'nikah', 'düğün', 'şölen', '200 kişi'] },
      { q: 'Paket ücreti tek seferlik mi, aylık abonelik var mı?', a: 'Evet, Nikahım paketleri tek seferlik ödeme ile satın alınır; aylık üyelik ücreti bulunmaz. Yalnızca ihtiyaç halinde ek yayın süresi, ek izleyici veya ek fotoğraf gibi ek paketleri ayrıca satın alabilirsiniz.',
        keywords: ['tek seferlik', 'aylık abonelik', 'ödeme', 'ek paket', 'subscription', 'her ay ücret'] },
      { q: 'Ödeme nasıl yapılır, kart bilgilerim güvende mi?', a: 'Ödemeler uygulama içi satın alma yöntemiyle Apple App Store veya Google Play hesabınız üzerinden gerçekleştirilir. Kart bilgilerinizi Nikahım’a girmeniz gerekmez; ödeme mağaza hesabınız üzerinden tamamlanır ve kredi kartı bilgileriniz Nikahım tarafından görülmez.',
        keywords: ['ödeme', 'app store', 'google play', 'kredi kartı', 'kart bilgileri', 'uygulama içi satın alma', 'güvenli ödeme'] },
      { q: 'Paketimi yükseltebilir / düşürebilir miyim?', a: 'Evet, paketinizi daha sonra yükseltebilirsiniz; mevcut paketiniz ile üst paket arasındaki fiyat farkını ödeyerek uygulama üzerinden yükseltme yapabilirsiniz. Ancak satın alınan bir paket daha düşük seviyeli bir pakete dönüştürülemez.',
        keywords: ['paket yükseltme', 'upgrade', 'fiyat farkı', 'downgrade', 'alt paket', 'üst paket'] },
      { q: 'İade alabilir miyim, kupon kodu nasıl kullanılır?', a: 'İade talepleriniz için Nikahım Destek ile iletişime geçebilirsiniz; talebiniz ve satın alma durumunuz incelenerek size bilgi verilir. Geçerli bir kampanya veya indirim kodunuz varsa paket satın alma sırasında kullanabilirsiniz.',
        keywords: ['iade', 'refund', 'para iadesi', 'kupon kodu', 'indirim kodu', 'kampanya', 'promosyon'] },
      { q: 'Gizli ek ücret var mı?', a: 'Hayır. Gösterilen paket fiyatları KDV dahil son fiyatlardır; gizli ücret veya sonradan eklenen bir Nikahım komisyonu bulunmaz. Yalnızca sizin ayrıca tercih ettiğiniz ek paketler ayrıca ücretlendirilir.',
        keywords: ['gizli ücret', 'kdv', 'ek ücret', 'komisyon', 'paket fiyatı', 'gizli masraf'] },
    ],
  },
  {
    title: 'Gizlilik ve Güvenlik',
    items: [
      { q: 'Kişisel bilgilerim güvende mi, 3. kişilerle paylaşılır mı?', a: 'Nikahım’da paylaştığınız kişisel bilgilerinizin gizliliğine önem verilir. Bilgileriniz izniniz olmadan reklam amacıyla kullanılmaz veya üçüncü kişilerle paylaşılmaz.',
        keywords: ['kişisel bilgi', 'gizlilik', 'veri güvenliği', 'üçüncü kişi', 'reklam', 'kvkk', 'privacy'] },
      { q: 'Davetli listemi ve masa planımı kimler görebilir?', a: 'Davetli listeniz ve masa planınız özeldir; uygulama üzerinden yalnızca siz görüntüleyebilirsiniz. Diğer davetlilere gösterilmez.',
        keywords: ['davetli listesi', 'masa planı', 'gizlilik', 'kim görebilir', 'özel liste'] },
      { q: 'IBAN bilgilerimi kimler görebilir?', a: 'IBAN bilginiz etkinlik sayfasının genelinde herkese gösterilmez. Yalnızca Altın Tak işleminin ödeme adımına ilerleyen davetlileriniz IBAN bilgisini görebilir.',
        keywords: ['iban', 'iban gizliliği', 'altın tak', 'kim görebilir', 'ödeme sayfası', 'hesap bilgisi'] },
      { q: 'Şifremi nasıl değiştiririm / unuttum ne yaparım?', a: 'Şifrenizi Nikahım uygulamasındaki Profilim bölümünden değiştirebilirsiniz. Şifrenizi unuttuysanız giriş ekranındaki “Şifremi Unuttum” seçeneğine dokunup ekrandaki adımları takip ederek sıfırlayabilirsiniz.',
        keywords: ['şifre değiştirme', 'şifremi unuttum', 'şifre sıfırlama', 'profilim', 'password', 'giriş'] },
      { q: 'Hesabımı veya etkinlik verilerimi silebilir miyim?', a: 'Evet. Etkinliğinizi ve ilgili verileri uygulama üzerinden silebilirsiniz. Hesabınızı tamamen silmek isterseniz Nikahım Destek ile iletişime geçebilirsiniz; ekibimiz hesap silme sürecinde size yardımcı olur.',
        keywords: ['hesap silme', 'veri silme', 'etkinlik silme', 'düğün silme', 'account delete', 'destek'] },
    ],
  },
  {
    title: 'Teknik ve Sorun Giderme',
    items: [
      { q: 'Hangi telefonları kullanabilirim, ne kadar boş alan gerekir?', a: 'Nikahım uygulamasının desteklendiği ve internet bağlantısı bulunan uyumlu iOS/Android telefon ve tabletlerden uygulamayı kullanabilir ve canlı yayın yapabilirsiniz. Uygulamayı rahatça yükleyebilmeniz için telefonunuzda yaklaşık 200 MB boş alan bulunmasını öneririz.',
        keywords: ['telefon', 'cihaz', 'uyumluluk', 'boş alan', '200mb', 'depolama', 'eski telefon', 'tablet'] },
      { q: 'Kamera / mikrofon / fotoğraf / bildirim izinleri neden isteniyor?', a: 'Kamera ve mikrofon izinleri, telefonunuzun kamerasını ve sesini kullanarak canlı yayın yapabilmeniz için gereklidir. Fotoğraf izni, telefonunuzdaki fotoğrafları albümünüze yüklemek istediğinizde gerekir. Bildirim izni zorunlu değildir; ancak düğün öncesi uyarı ve hatırlatmaları görebilmek için açık tutmanızı öneririz.',
        keywords: ['kamera izni', 'mikrofon izni', 'fotoğraf izni', 'bildirim izni', 'izinler', 'galeri'] },
      { q: 'Yayın başlamıyor, ne yapmalıyım?', a: 'Önce internet bağlantınızı kontrol edin ve Canlı Yayın ekranındaki kamera, mikrofon ve internet göstergelerinin yeşil olduğundan emin olun. Her şey normal görünmesine rağmen yayın başlamıyorsa uygulamayı tamamen kapatıp yeniden açın ve tekrar deneyin. Sorun devam ederse Nikahım Destek’e ulaşın.',
        keywords: ['yayın başlamıyor', 'yayına geçemiyorum', 'kamera', 'mikrofon', 'internet', 'yeşil kontrol', 'uygulamayı yeniden aç'] },
      { q: 'Yayın sürekli donuyor / görüntü kalitesi düşük.', a: 'Önce yayın ekranındaki bağlantı kalitenizi kontrol edin. Bağlantınız zayıfsa mümkünse daha stabil bir Wi-Fi ağına geçin. Donma devam ediyorsa yayını yeniden başlatıp bir alt çözünürlük seçin; bu çoğu zaman donmayı bitirir. Sorun çözülmezse Nikahım Destek’e ulaşın.',
        keywords: ['yayın donuyor', 'donma', 'takılma', 'buffering', 'görüntü kalitesi', 'bulanık', 'wifi', 'çözünürlük'] },
      { q: 'Davetliler yayını izleyemiyor.', a: 'Davetlilerin doğru Nikahım linkini açıp ad-soyad bilgileriyle etkinlik sayfasına ulaştığından emin olun. Siz yayını başlattığınızda görüntü aynı sayfada otomatik açılır. Buna rağmen davetliler hiçbir görüntü göremiyorsa hemen Nikahım Destek ile iletişime geçin.',
        keywords: ['davetli izleyemiyor', 'yayın görünmüyor', 'misafir', 'yayın açılmıyor', 'siyah ekran', 'kimse göremiyor'] },
      { q: 'Paket satın aldım ama hesabıma tanımlanmadı.', a: 'Önce Nikahım uygulamasını tamamen kapatıp yeniden açarak paket durumunuzu kontrol edin. Satın aldığınız paket hâlâ hesabınıza tanımlanmadıysa Nikahım Destek ile iletişime geçin; satın alma durumunuzu kontrol edelim.',
        keywords: ['paket tanımlanmadı', 'satın alma', 'ödeme yaptım', 'paket görünmüyor', 'app store', 'google play', 'işlem tamamlanmadı'] },
      { q: 'Düğün günü sorun yaşarsam kime ulaşırım?', a: 'Düğün veya nikah öncesinde ya da etkinlik sırasında bir sorun yaşarsanız Nikahım Destek ekibine Canlı Destek veya WhatsApp üzerinden ulaşabilirsiniz. Şu an için telefon desteği bulunmamaktadır.',
        keywords: ['düğün günü', 'destek', 'canlı destek', 'whatsapp', 'teknik destek', 'acil', 'telefon desteği'] },
    ],
  },
];
